### ISSUE TITLE
Error when running abc_conditions

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#137]
@kmantel I get an error with the condition handling when I try:

    python abc_conditions.py  -run

i.e. actually running the example with the execution engine. Only showing up after merging #127

```
Traceback (most recent call last):
  File "/Users/padraig/opt/miniconda3/envs/py38a/lib/python3.8/site-packages/modeci_mdf/execution_engine.py", line 839, in parse_condition
    typ = getattr(graph_scheduler.condition, condition["type"])
TypeError: 'Condition' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "abc_conditions.py", line 119, in <module>
    main()
  File "abc_conditions.py", line 104, in main
    eg = EvaluableGraph(mod_graph, verbose=verbose)
  File "/Users/padraig/opt/miniconda3/envs/py38a/lib/python3.8/site-packages/modeci_mdf/execution_engine.py", line 711, in __init__
    conditions = {
  File "/Users/padraig/opt/miniconda3/envs/py38a/lib/python3.8/site-packages/modeci_mdf/execution_engine.py", line 712, in <dictcomp>
    self.graph.get_node(node): self.parse_condition(cond)
  File "/Users/padraig/opt/miniconda3/envs/py38a/lib/python3.8/site-packages/modeci_mdf/execution_engine.py", line 845, in parse_condition
    raise TypeError("Invalid condition dictionary: %s" % condition) from e
TypeError: Invalid condition dictionary: Condition (None), type = BeforeNCalls, args = {'dependencies': 'input0', 'n': 1}

```

**Comment by kmantel** [comment]
There are a few things going on here
1. Scripts are not run using the `-run` argument during testing, so these are liable to break silently (which is why this wasn't caught)
2. `mdf.Graph`s created using mdf classes in a script results in the `node_specific` attribute of `ConditionSet` containing `Condition` objects, while those created via `load_mdf` result in the `node_specific` attribute of `ConditionSet` containing dictionaries

Since only the latter case in 2. is tested, the parser was designed for this. #138 works around this, handling both, but this inconsistency doesn't seem ideal

**Comment by pgleeson** [comment]
@kmantel Yes it's true that the tests don't test the models when run directly from Python, but they do test them all when they are reloaded from json/yaml. 

Ideally it shouldn't matter, but in this case here it does, as the model is being created in Python with a Condition object (which was failing), it's saved/reloaded as a dict (which was passing). Reloading the json/yaml as a dict is expected as this says the type of node_specific inside ConditionSet is a dict not Condition: https://github.com/ModECI/MDF/blob/9fc53d9f88c6e243a527ef96c47fda66fe560088/src/modeci_mdf/mdf.py#L679

That can be fixed/tested, but for now some of the branches are failing on py3.7 (but not 3.9): https://github.com/ModECI/MDF/actions. I see there were some major changes on the mdf branch of PNL yesterday, are you sure those work with 3.7/8?

**Comment by kmantel** [comment]
> they do test them all when they are reloaded from json/yaml.

When is this? It doesn't seem to be during automated testing because when running `run_test_function_json.py` with `-run`, it fails on the current development branch. If it's important that `-run` behaves correctly, and I think it is, then we should add it to the test suite, whether as additional cases or the primary case for examples.

> Reloading the json/yaml as a dict is expected as this says the type of node_specific inside ConditionSet is a dict not Condition

In this case, should `node_specific` and `termination` be in `ConditionSet.allowed_children` instead of allowed_fields? This seems to be the pattern in other mdf objects, where attributes that correspond to another mdf object are children rather than fields.

>  I see there were some major changes on the mdf branch of PNL yesterday, are you sure those work with 3.7/8?

This is in part due to dependency problems; I've opened an issue relating to the specific error in e.g. https://github.com/ModECI/MDF/runs/3608055512?check_suite_focus=true here: https://github.com/LEMS/pylems/issues/61. For now, I've reverted to the old version
For

**Comment by pgleeson** [comment]
Re tests on json yaml, this happens here: https://github.com/ModECI/MDF/blob/a67e0b5283b203de4ab33d8690e7967c5dd7b058/tests/test_scheduler.py#L4
A number of the examples are loaded in in json/yaml and run through one step of execution. 

Re running with '-run', it's possible this line could be updated to include that arg: https://github.com/ModECI/MDF/blob/development/tests/test_examples.py#L99, so the examples run/tested in python and the argument gets ignored if this option is not supported.

> In this case, should node_specific and termination be in ConditionSet.allowed_children instead of allowed_fields? This seems to be the pattern in other mdf objects, where attributes that correspond to another mdf object are children rather than fields.

Yes. @mraunak could you look at the above 2 points? Should just be small changes, but it will be a week or two before I get to them.

Ok, problem fixed in pylems, we'll make a new release, but great that the tests are passing.

**Comment by mraunak** [comment]
@pgleeson The above issues have been resolved. The allowed_fields of conditionSet (node_specific and termination) have been converted to allowed_fields. The implementation is passing all the test cases and it is available at the doc_cleanup branch.
