### ISSUE TITLE
int and float type mismatch for running ONNX models with the MDF execution engine

### ISSUE THREAD

**Issue by rpradyumna** [ModECI/MDF#154]
When an MDF model translated from ONNX is run, the datatype of the constant parameters is by default int unless there is a floating point number (e.g., 2.1, 2.5 etc.). If a node in the model operates on this parameter along with a float input (e.g., Add with 0.2 and 1), then, when we run the model with the MDF execution engine, we get an error that the operand datatypes do not match. Could we fix this? One approach is to read constants as floats by default (in the evaluate function of the Evaluable Parameter class.

The issue can be reproduced by running simple_ab.py with the "-run" command line argument, and changing one of the test_values to a decimal number (e.g., [0, 1, 2] to [0.1, 1, [1,2] in https://github.com/ModECI/MDF/blob/77a6c6c1c15dfecaab981a1867c03cf99cf1d040/examples/ONNX/simple_ab.py#L94)

Error message: "onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) of Optype (Add) bound to different types (tensor(double) and tensor(int64) in node (Ad_Add)."

Verbose output from the execution engine: "Add_1 is evaluating ONNX function onnx_ops.add(A, B) with {'A': 0.1, 'B': 1}"

**Comment by kmantel** [comment]
I came across this same problem and have been using a solution locally. I don't think it's due to something related to translating, but instead from casting in the `evaluate` method of NeuroMLlite: https://github.com/NeuroML/NeuroMLlite/blob/85461eaa300430970e9f45b68fadcc4c96833b7f/neuromllite/utils.py#L207 which we use as `evaluate_params_nmllite`. 

> One approach is to read constants as floats by default (in the evaluate function of the Evaluable Parameter class.

I think this could end up with the opposite problem where the ONNX function expects an int but gets a float instead.

I haven't opened a PR with my solution yet because it depends on #153 (although it could probably be reworked not to). It's now pushed to the onnx branch on my fork at https://github.com/kmantel/MDF/tree/onnx ([231f1cf](https://github.com/kmantel/MDF/commit/231f1cf6b06a9347751600d9290e8eda65629154))

**Comment by pgleeson** [comment]
Yes, I think some of the motivation for returning an int when it's a float like 1.0 was down to presentation in graphs, GUIs etc. If the nmlllite functions are being used in a wider context then it should probably defgault to giving back what was put in.

Unfortunatley not much will happen from my side until the ModECI grant is submitted, but then one of my first tasks will be to extract the JSON/serialsisation/definition functioanlity out of NMLlite and make it a standalong package, whith more comprehensive test etc.
