### ISSUE TITLE
Update conditions example

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#254]
The existing conditions example (https://github.com/ModECI/MDF/tree/main/examples/MDF#conditions-example) should be updated to provide a clear outline of the various types of conditions allowed in MDF

- [x] remove input0 for now & just have nodes ABC
- [x] Add summary at end of execution of https://github.com/ModECI/MDF/blob/main/examples/MDF/abc_conditions.py to show the sequence of execution of the nodes (i.e it matches what was expected from the conditions)
- [x] Update the graphical export to more clearly summarise what the conditions are

**Comment by Ivy8127** [comment]
I've been running the code locally and it's all good. However, how do I generate the graph model inside my python 3.7 env. I noticed the sys.argv -graph line of code in [](https://github.com/ModECI/MDF/blob/main/examples/MDF/simple.py) on line 85 which renders the graph. Is it possible in a python file or should I just test it on a Jupyter notebook?

**Comment by Ivy8127** [comment]
By summary of execution, do you mean adding a docstring within the .py file?

**Comment by Ivy8127** [comment]
I've finally gotten around to understanding conditions and how graph scheduler handles the execution of nodes based on conditions. I'm trying to run changes on execution_engine.py locally (which contains the logic on how the Graph is being evaluated) but no changes are happening on the abc_conditios.py file which imports EvaluableGraph from the execution engine. What could be the issue?

**Comment by pgleeson** [comment]
@Ivy8127 Maybe try with some of the examples first which don't contain conditions, so the behaviour it fully handled in the execution_engine.py, e.g.  https://github.com/ModECI/MDF/blob/main/examples/MDF/states.py.

Modifying the behaviour of the execution_engine should be easier to track there. What are you trying to modify by the way? The comments printed when it's excuted at each time step?

**Comment by davidt0x** [comment]
hey @Ivy8127, not sure i am following your question but if you are modifying execution_engine.py and not seeming to effect anything make sure you have installed the mdf package as editable (use `pip install -e` when installing the repo). Otherwise, pip will make a copy of the source tree and move it to site packages and any changes you make locally will not be reflected in the site-packages version. If this is obvious or not your issue sorry, it just sounds like a common bug.

**Comment by Ivy8127** [comment]
> hey @Ivy8127, not sure i am following your question but if you are modifying execution_engine.py and not seeming to effect anything make sure you have installed the mdf package as editable (use `pip install -e` when installing the repo). Otherwise, pip will make a copy of the source tree and move it to site packages and any changes you make locally will not be reflected in the site-packages version. If this is obvious or not your issue sorry, it just sounds like a common bug.

That solved the problem actually thanks! Okay, I've been able to print out the order of execution of the nodes as per the conditions in the python script (abc_conditions.py) but it's still verbose. ``` graph_scheduler.Scheduler.run() ``` achieves this but prints out all the Node attribute information such as metadata, input_ports, etc. Is there a way in MDF to get a Node object to only print out its id, it seems that the output by the scheduler will be less verbose with this. So it prints out sth like `[{'A'}, {'A'}, {'B'}, {'A'}, {'C'}, {'A'}, {'B'}, {'A'}, {'A'}, {'C'},{'A'}]`

instead of : (essentially correct just a bit verbose?)
`[{Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='B', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_B', value='count_B + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='C', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_C', value='count_C+ 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', 
value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='B', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_B', value='count_B + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='C', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_C', value='count_C+ 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)]), Node(metadata=None, id='B', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_B', value='count_B + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}, {Node(metadata=None, id='A', input_ports=[InputPort(metadata=None, id='input_port1', shape=(1,), type=None)], functions=[], parameters=[Parameter(metadata=None, id='count_A', value='count_A + 1', default_initial_value=None, time_derivative=None, function=None, args=None, conditions=[])], output_ports=[OutputPort(metadata=None, id='output_1', value='input_port1', shape=None, type=None)])}]`

**Comment by pgleeson** [comment]
@Ivy8127 You should be able to turn off the verbosity by changing this: https://github.com/ModECI/MDF/blob/development/examples/MDF/abc_conditions.py#L84 and then you can just go through the final state of the output ports using commands like this: https://github.com/ModECI/MDF/blob/development/examples/MDF/states.py#L77. That will at least give the final count for the individual nodes, and then you can try changing the conditions to see how many times they get run. We can discuss in more detail on how to dive deeper into the individual nodes on monday.
