### ISSUE TITLE
Rename modeci_mdf to modeci

### ISSUE THREAD

**Issue by davidt0x** [ModECI/MDF#34]
Rename top-level package from `modeci_mdf` to `modeci`. `mdf` is already a sub-module within. (actually called `MDF` now but will be lowercased if we conform to PEP8) With this I can setup a `modeci` pypi package as well and setup automatic publish on tagged releases.

**Comment by pgleeson** [comment]
Let me ruminate on this a bit more. I thought of calling the package that initially, but decided against it, I think mainly because ModECI's the name of the Initiative... You don't install Apache or Mozilla (let's think big here)... There could be a ModECI database of models, various working groups, tools, etc. 

Pypi packaging is not super urgent, and many things can change in phase II...

**Comment by davidt0x** [comment]
Ok, just remember there are two issues here, I have kind of conflated them sorry. We can have a different name for the import package and pypi distribution package. This all gets very confusing, see the definition [here](https://packaging.python.org/glossary/). 

Maybe what we should do is change the top-level import package name to `modeci`. From a user perspective, things would look like: `import modeci.mdf` or `from modeci.mdf import Model, ModelGraph`, or `from modeci.mdf import *`. The pypi distribution package (the name that people use in pip install and install_requires) could still be called `modeci-mdf`. This would just result in a import package called `modeci.mdf` on the users site-packages. Another future pypi distribution package `modeci-models` might install an import package `modeci.models`. They could also install everything with yet another pypi distribution package just called `modeci`. The thing to keep clear is that this repo we are working on now contains only the sub-package for MDF. Down the line, if we wanted to have a top-level modeci package we would probably need to place this whole repo (maybe as a git sub-module) into another top-level `modeci` repo. I have never set something like this up but I think what we want is a namespace package called `modeci` (see [here](https://packaging.python.org/guides/packaging-namespace-packages/))

So for this repo, i think the change would be to rename modeci_mdf top-level directory to modeci. Within this make sure that it does not contain a `__init__.py` so that `modeci` is a namespace package. In setup.cfg the package name would be modeci-mdf. Does this make sense? Later down the line we can worry about creating an actual modeci distribution pacakge.

**Comment by jdcpni** [comment]
This all sounds good to me.


jdc



On Mar 18, 2021, at 10:48 AM, David Turner ***@***.******@***.***>> wrote:



Ok, just remember there are two issues here, I have kind of conflated them sorry. We can have a different name for the import package and pypi distribution package. This all gets very confusing, see the definition here<https://packaging.python.org/glossary/>.

Maybe what we should do is change the top-level import package name to modeci. From a user perspective, things would look like: import modeci.mdf or from modeci.mdf import Model, ModelGraph, or from modeci.mdf import *. The pypi distribution package (the name that people use in pip install and install_requires) could still be called modeci-mdf. This would just result in a import package called modeci.mdf on the users site-packages. Another future pypi distribution package modeci-models might install an import package modeci.models. They could also install everything with yet another pypi distribution package just called modeci. The thing to keep clear is that this repo we are working on now contains only the sub-package for MDF. Down the line, if we wanted to have a top-level modeci package we would probably need to place this whole repo (maybe as a git sub-module) into another top-level modeci repo. I have never set something like this up but I think what we want is a namespace package called modeci (see here<https://packaging.python.org/guides/packaging-namespace-packages/>)

So for this repo, i think the change would be to rename modeci_mdf top-level directory to modeci. Within this make sure that it does not contain a __init__.py so that modeci is a namespace package. In setup.cfg the package name would be modeci-mdf. Does this make sense? Later down the line we can worry about creating an actual modeci distribution pacakge.

**Comment by pgleeson** [comment]
Closing for now as I believe the current name works fine...
