### ISSUE TITLE
Does PsyNeuLink v0.13.0.0  require latest pytorch, i.e. we can't use it?

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#381]
Some tests here were failing after the release of PsyNeuLink v0.13.0.0, which led to the installation of pytorch 1.13.

See https://github.com/ModECI/MDF/issues/279 for why we require pytorch 1.11 still...

PNL version pinned for now:
https://github.com/ModECI/MDF/blob/470cffd211b099b8a3679cbc180c07f442461579/setup.py#L8

**Comment by davidt0x** [comment]
@pgleeson, can you share logs on failing tests. MDF should support latest pytorch right now. I had fixed this back in August but never closed the issue sorry.

**Comment by pgleeson** [comment]
Here are some tests with failures, with the latest PNL and pytorch 1.13.1
https://github.com/ModECI/MDF/actions/runs/3957271830

Many failures at the ACT-R stage, but https://github.com/ModECI/MDF/actions/runs/3957271830/jobs/6777433605 at least fails at pytorch stage

**Comment by davidt0x** [comment]
Ah ok, I think I know what is going on. It looks like some issues with new torchvision models. I was just upgraded to torch 1.13 on my side. I think the actual issue is a new version of torchvision. 1) There are some big models we need to skip testing in CI, they will be too slow on CPU and\or run out of memory. Let me see what the torchvision folks are skipping in there CI and I will try to match their logic 2) Looks like some newer models are failing to match results. I will need to dig into these ones.

Overall, this might take a bit of time. A workaround is probably to pin torchvision to an older working verison.
